DEFRA/ado-pipeline-common

- tests/devops/vars/regional/dev-northeurope.yaml
- tests/devops/vars/regional/dev-westeurope.yaml
- tests/devops/vars/regional/tst-northeurope.yaml
- tests/devops/vars/regional/tst-westeurope.yaml
Fixed the instance numbers in the Test varaiables.
AB#194442
> 194442: Test Variable Update

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/BuildAndPushDockerImage.ps1
- templates/powershell/build/Extract-CodeVersion.ps1
- templates/powershell/build/GetSet-CodeVersion.ps1
- templates/powershell/build/HelmLintAndPublish.ps1
- templates/steps/common-app-cd.yaml
- templates/steps/dotnet-build.yaml
- templates/steps/nodejs-build.yaml
- templates/steps/security-scan-application.yaml
- templates/steps/security-scan-container.yaml
- tests/devops/vars/regional/dev-northeurope.yaml
- tests/devops/vars/regional/dev-westeurope.yaml
- tests/devops/vars/regional/tst-northeurope.yaml
- tests/devops/vars/regional/tst-westeurope.yaml
Added common CI pipeline and related steps and powershell scripts
Change related to AB#194442
- [x ] I have linked all related work items to this Pull Request
- [ x] I can build the solution with no warnings or errors
- [ x] I have added tests that prove my feature is effective
- [ x] I have checked that impacted tests are passing
- [ x] I have added necessary documentation (if appropriate)
> 194442: CI Pipeline

- templates/powershell/build/BuildAndPushDockerImage.ps1
- templates/powershell/build/HelmLintAndPublish.ps1
Related to AB#195091
- [ x] I have linked all related work items to this Pull Request
- [ x] I can build the solution with no warnings or errors
- [ x] I have added tests that prove my feature is effective
- [ x] I have checked that impacted tests are passing
- [ x] I have added necessary documentation (if appropriate)
> 195091: Image and helm prefix

- templates/powershell/build/Extract-CodeVersion.ps1
AB#241378
- [x ] I have linked all related work items to this Pull Request
- [x ] I can build the solution with no warnings or errors
- [x ] I have added necessary documentation (if appropriate)
> 241378: Read version from VERSION file

- templates/pipelines/common-app-ci.yaml
- templates/steps/sonar-analysis-prepare.yaml
- templates/steps/sonar-analysis.yaml
> 242766 : Sonar analysis task

- templates/pipelines/common-infrastructure-deploy.yaml
- templates/steps/initialize.yaml
- tests/devops/pipelines/pipeline.common.integrationtest.yaml
> 229542: Deployment timeout

- templates/pipelines/common-infrastructure-deploy.yaml
- templates/steps/initialize.yaml
- templates/steps/validate-deploy-arm-template.yaml
> 231044:Token replace at task level

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/HelmLintAndPublish.ps1
- templates/steps/common-app-cd.yaml
AB#249931
- [ x] I have linked all related work items to this Pull Request
- [ x] I can build the solution with no warnings or errors
- [ x] I have checked that impacted tests are passing
- [ x] I have added necessary documentation (if appropriate)
> 249931: Build mulitple helm charts

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/HelmLintAndPublish.ps1
- templates/powershell/build/ImportSecretsToKV.ps1
- templates/powershell/build/ValidateConfigFile.ps1
- templates/steps/common-app-cd.yaml
> 249931: Helm script fix

- templates/powershell/build/HelmLintAndPublish.ps1
Added condition to check chartDirectory exist so that this script can be reused for helm library publish.
AB#248953
> 248953: added chartDirectory condition

- templates/steps/powershell.yaml
- templates/steps/validate-deploy-arm-template.yaml
Fix the KV secrets download task parameter
Change the script type to PS Code for the scripts to work with Ubuntu agents
AB#248355
> 248355: Fix the KeyVault secrets download

- templates/powershell/build/BuildAndPushDockerImage.ps1
Description:
Enhanced Common CI Pipeline to push db migration Image if db docker file is present in the application repo.
AB#256774 
Pipeline run: Below pipeline run pushes 2 images(App and DB) to ACR.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=388702&view=logs&j=e3a28775-a7cf-5411-f920-f6ba8cda4951&t=351f354b-313c-5c62-5331-a5030ac78a42
> 256774 : Common CI Pipeline upgrade to Build and push db migration Image to ACR

- templates/steps/appconfig-import.yaml
* Fix for keyvault reference
AB#258378
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=390772&view=results
- [x ] I have linked all related work items to this Pull Request
- [ x] I can build the solution with no warnings or errors
- [ x] I have added necessary documentation (if appropriate)
> 258378 : Appconfigkvfix

- templates/pipelines/common-infrastructure-deploy.yaml
Added support for Azure CLI Script Type. 
AB#249140
> 249140: Deployment script

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Build-Helm-KVSecretsRoleAssignments.ps1
Creates 'keyvault-secrets-role-assignment.yaml' template in Application's Infra Helm chart and Appends required Keyvault secretname values to values.yaml file.
[AB#261688](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261688) 
> 261688: Insert KeyVault Rbac template in Infra helm chart folder

- templates/powershell/build/Build-Helm-KVSecretsRoleAssignments.ps1
Added Logic to remove servicename from the secretname when creating KV RBAC helm values.
For e.g. "ffc-demo-payment-web-COOKIE-PASSWORD" will get replace with "COOKIE-PASSWORD"
[AB#261143](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261143)
> 261143 : Common CI - KV RBAC changes

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/BuildAndPushDockerImage.ps1
This change will build docker image using shared acr which is public.
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=403855&view=results
- [x ] Story Work items associated (not Tasks)
- [ x] Successful testing run(s) link provided
- [ x] Title pattern should be `{work item number}: {title}`
- [ x] Description covers all the changes in the PR
> 262177: Build Docker using Acr

- templates/powershell/build/BuildAndPushDockerImage.ps1
261293: Updated the docker build script to specify the shared ACR for the DB Migrations Docker file. Also added the debug logs that were missing for the function parameters.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#261293](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261293) and builds on [404115](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=404115&view=results)
Pipeline completed successfully  [404115](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=404115&view=results)
> 261293: Updated the docker build script to specify the shared ACR for the DB Migrations Docker file

- docs/AppBuildAndDeploy.md
- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/BuildAndPushDockerImage.ps1
This change will build docker image using self hosted agent 
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=406284&view=logs&j=71f8ef09-b53f-586a-463a-bf5802c5c97f
> 262177 :  Build Docker Image 

- docs/PortalAppBuildAndDeploy.md
- templates/pipelines/common-portal-app-ci.yaml
- templates/powershell/build/BuildAndDeployBackstageApp.ps1
- templates/steps/portal-cd.yaml
New CI/CD pipeline for Backstage portal related to work item [AB#263292](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/263292)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=405794&view=logs&j=61743bb8-9454-5f75-42e5-071c36d248b1&t=18c482fc-d74d-578b-2951-36da3d0b2a9f
- [x ] Story Work items associated (not Tasks)
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [x ] Description covers all the changes in the PR
- [x ] This PR contains documentation
> 263292 : Backstage Portal

- templates/config/schema.json
- templates/steps/appconfig-import.yaml
The fix include change in json schema and fixing PowerShell version to 7.4.0-1.deb
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=408846&view=logs&j=e3a28775-a7cf-5411-f920-f6ba8cda4951&t=57c2ba0e-cb97-5f5f-68da-00d906da7b7b
> 262177 : Json schema validation fix

- templates/pipelines/common-portal-app-ci.yaml
- templates/steps/security-scan-container.yaml
Snyk container scan accepts additional policy file as additionalArguments. Change include supplying Policy File path 
[AB#268744](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/268744)
Tested ffc-demo-web as well 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=411198&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=4806
> 268744 : Snyk Policy File Path

- templates/pipelines/common-portal-app-ci.yaml
- templates/powershell/build/BuildAndDeployBackstageApp.ps1
[AB#263387](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/263387)
Added unit test task 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=413955&view=results
> 263387 : Portal Unit Test

- docs/AppBuildAndDeploy.md
- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/HelmLintAndPublish.ps1
- templates/steps/common-app-cd.yaml
Moved Helm Lint to separate job to fast fail and run other jobs in parallel.
[AB#271636](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/271636)
[AB#271717](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/271717)
Also updated the condition for CD process to deploy the main and pr build to dev env only
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=412609&view=logs&s=8553b77f-381e-567b-55f9-6a513ebf8abf
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=412674&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=415005 …
> 271636 : helm lint

- templates/pipelines/common-app-ci.yaml
- templates/pipelines/common-portal-app-ci.yaml
[AB#268744](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/268744)
Change will skip adding secrets if no variable groups provided for the pipeline
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=415125&view=logs&s=aee76c8a-1d8b-5149-1924-86de92a850c9
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=415193&view=logs&j=61743bb8-9454-5f75-42e5-071c36d248b1
> 273567 : skip adding secrets if no variable groups

- templates/pipelines/common-infrastructure-deploy.yaml
Added useSystemAccessTokeninScript to common-infrastructure-deploy.yaml pipeline template
Relates to ADO Work Item [AB#231463](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/231463)
> 231463: Added useSystemAccessTokeninScript

- templates/pipelines/common-app-ci.yaml
- templates/pipelines/common-portal-app-ci.yaml
- templates/steps/dotnet-build.yaml
- templates/steps/nodejs-build.yaml
- templates/steps/sonar-analysis-prepare.yaml
Added task to publish the code coverage and updated code coverage path
[AB#278172](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/278172)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=422655&view=results
> 278172: code coverage

- templates/pipelines/common-techdocs-publish.yaml
- templates/powershell/build/BuildAndDeployBackstageApp.ps1
- templates/powershell/build/PublishTechDocs.ps1
[AB#279550](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/279550): Added additional pipeline to generate techdocs
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=425342&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=425339&view=results
> 279550 : techdocs

- templates/pipelines/common-app-ci.yaml
- templates/pipelines/common-portal-app-ci.yaml
- templates/steps/sonar-analysis-prepare.yaml
[AB#278019](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/278019)
The change includes updating sonar properties file path 
> 278019: Sonar project file

- templates/pipelines/common-app-ci.yaml
- templates/pipelines/common-portal-app-ci.yaml
- templates/steps/sonar-analysis-prepare.yaml
[AB#278019](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/278019)
Fix for lcov report path
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=430089&view=results
> 278019: lcov report path

- templates/powershell/build/ImportAppConfig.ps1
[AB#284701](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/284701)
Added config file check. If not found task will continue without error
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=430605&view=logs&j=e3a28775-a7cf-5411-f920-f6ba8cda4951&t=351f354b-313c-5c62-5331-a5030ac78a42
> 284701: File check validation

- templates/pipelines/common-app-ci.yaml
- templates/powershell/modules/resource-provision/resource-provision.psm1
- templates/steps/nodejs-build.yaml
[AB#291239](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/291239)
Fix includes 
Avoid use of NodeJSAppBuild variable group
Queues and Topics are not mandatory for all services
Service of type POC should be deployed only to SND1, SND2 and SND3 environment
https://dev.azure.com/defragovuk/DEFRA-EUTD-EHCO/_build/results?buildId=441921&view=logs&s=8553b77f-381e-567b-55f9-6a513ebf8abf
> 291239: Fix for CI build

- templates/pipelines/common-app-ci.yaml
- templates/pipelines/common-portal-app-ci.yaml
- templates/pipelines/common-techdocs-publish.yaml
- templates/steps/appconfig-import.yaml
- templates/steps/common-app-cd.yaml
- templates/steps/portal-cd.yaml
- templates/steps/post-deployment-tests.yaml
- templates/steps/pre-deployment-tests.yaml
- templates/steps/secrets-import-kv.yaml
[AB#295475](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/295475)
Updated the checkout path to match the repo name.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=449466&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=449451&view=results
> 295475: Tidy up warnings on CI pipeline

- templates/powershell/build/Extract-CodeVersion.ps1
[AB#295473](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/295473)
Friendly message as per jenkins code
> 291239: Updated Version Message

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Set-SonarCloud.ps1
- templates/steps/sonar-analysis-prepare.yaml
Changes to create the sonar project if it does not exist as part of the CI pipeline.
Relates to ADO Work Item [AB#291837](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/291837)
N/A
N/A
> Sonar cloud project and branch creation fix

- docs/AppBuildAndDeploy.md
- templates/pipelines/common-app-ci.yaml
- templates/steps/pre-deployment-tests.yaml
[AB#296207](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296207)
Added conditions to run selected pre deployment tests
1. PR Branch test: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=458454&view=results
2.  Master branch test: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=458334&view=results
3. Feature branch test: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=456923&view=results
4. Default Test Value: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=459301&view=results
> 291239:  Run selected Pre deploy tests

- templates/steps/security-scan-container.yaml
- templates/steps/sonar-analysis-prepare.yaml
Added support for Sonar opencover format. 
Added exclusion for base image vulnerabilities for Snky.
[AB#291974](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/291974)
> 291974: Sonar and Snky updates

- docs/AppBuildAndDeploy.md
- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/TagRelease.ps1
- templates/steps/tag-and-release.yaml
[AB#299102](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/299102)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=461237&view=results
https://github.com/DEFRA/ffc-demo-web/releases
> 299102: Tag and Release

- templates/powershell/build/PublishTechDocs.ps1
*Link to the relevant work items: [AB#305912](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305912)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=464595&view=results
> 305912: use requirements txt file

- templates/powershell/modules/app-config/app-config.psm1
Remove the spaces from the KV References.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A
> Remove the spaces from the AppConfig KV references.

- templates/pipelines/common-app-ci.yaml
[AB#303370](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/303370)
appDeployConfig:
filepath: "./appConfig"
filetype: "yaml"  
variableGroups: 
- ffc-demo-web-<environment>
variables:
- ffc-demo-web-APPINSIGHTS-CONNECTIONSTRING
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=464961&view=results
> 303370: Simplify Group Variables parameter name

- templates/powershell/build/Set-SonarCloud.ps1
Update sonar project properties to analyze change
N/A
N/A
> Update Sonar project properties to analysis only changed code

- templates/powershell/build/Set-SonarCloud.ps1
Fix the input parameters for the sonar project create api.
N/A
N/A
> Fix the sonar project create api input parameters.

- templates/powershell/build/TagRelease.ps1
Fix the logic to read a release on git repository.
N/A
N/A
> Fix the logic to read a release on git repository.

- templates/powershell/build/TagRelease.ps1
Fix the variable initialisation issue.
N/A
N/A
> Fix the variable initialisation issue.

- templates/powershell/build/Extract-CodeVersion.ps1
Improve ADO Logging output on the UI.
[https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=486604&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=486593&view=results](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=486618&view=results)
> Improve Log Output

- templates/steps/sonar-analysis-prepare.yaml
Added config for sonar to analyse code on the branches.
[AB#292476](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/292476)
> 292476:Dotnet code coverage for branches

- templates/powershell/build/Set-SonarCloud.ps1
Change the sonar project search api from component search to tree as seach returns incorrect matches for similar names.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
N/A
N/A
> 326112: Change the sonar project search api from component search to tree as seach returns incorrect matches for similar names.

- templates/powershell/build/Set-SonarCloud.ps1
Correct the sonar project check
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
> 326112: Correct the sonar existing project check condition.

- templates/powershell/build/Build-Helm-KVSecretsRoleAssignments.ps1
- templates/powershell/modules/resource-provision/resource-provision.psm1
Below task were failing in CI pipeline for empty infra helm chart scenario.
"Add KV Roleassignment template to ASO Infra helm chart"
"Provision Resources for Tests"
This PR is to fix above bug
Relates to ADO Work Item [AB#334643](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/334643)
> 334643: Bug fix for empty infra helm chart scenario

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Extract-CodeVersion.ps1
*Link to the relevant work items:*
[AB#344286](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/344286)
1. Added -alpha.$buildid to the version for both feature branch and PR branch builds
2.  Build will fail if the developer has not updated the version in the package.json
Feature Branch Build: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=508020&view=results
PR Build:  https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=508026&view=results
> 344286: Increment builds on feature branch

- templates/powershell/build/HelmLintAndPublish.ps1
*Link to the relevant work items: *
[AB#351721](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/351721)
Reproduced the issue: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=518300&view=results
Passed after fix: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=518302&view=results
> 351721: Fix to check empty values file

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/ImportAppConfig.ps1
- templates/powershell/modules/app-config/app-config.psm1
- templates/steps/appconfig-import.yaml
Correct the CRUD logic to import the config keys for the App CI Pipeline.
Relates to ADO Work Item [AB#307421](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/307421)
N/A
N/A
> 307421: App CI Pipeline - Import correct config keys

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Add-RepositoryToGitHubAppInstallation.ps1
Add new script for github app installation. This will setup the GitHub App 'Azure Pipelines' only on first run automatically. Uses github conn PAT & has condition logic. script is generic. fixes scaffold issue.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=532281&view=logs&j=71f8ef09-b53f-586a-463a-bf5802c5c97f&t=4d511448-a31e-5753-496c-388e8c11c474
> Add new github app installation

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Add-RepositoryToGitHubAppInstallation.ps1
Fix org logic so it's Dynamic
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=535014&view=logs&j=d9795cd7-f90d-55a9-977f-24cc132aa6e8&t=75a2aaf9-89c4-59f6-e50d-0f18b682b578
> Fix Organisation Logic

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Add-RepositoryToGitHubAppInstallation.ps1
- templates/powershell/build/Set-SonarCloud.ps1
- templates/steps/sonar-analysis-prepare.yaml
Refactor secrets usage in common app pipeline.
Relates to ADO Work Item [AB#366173](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/366173)
N/A
N/A
> 366173: Read secrets from KV in pipeline and refactor secrets usage in script.

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/Extract-CodeVersion.ps1
*Link to the relevant work items:*
[AB#368849](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/368849)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=540208&view=logs&j=71f8ef09-b53f-586a-463a-bf5802c5c97f&t=71f8ef09-b53f-586a-463a-bf5802c5c97f
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=540223&view=logs&j=d9795cd7-f90d-55a9-977f-24cc132aa6e8
> 368849 : Run git commands for public and private GitHub Repositories 

- templates/powershell/build/BuildAndPushDockerImage.ps1
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
> Remove AcrRepoName  To Lower conversation

- templates/steps/dotnet-build.yaml
*Link to the relevant work items: *
[AB#380413](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/380413)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=559390&view=results
> 380413: opencover report for .net project

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/HelmLintAndPublish.ps1
Implemented Helm validation on CI stage. 
[AB#338415](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/338415)
> 338415: Helm template validation

- templates/powershell/modules/app-config/app-config.psm1
Fix to preserve service specific Sentinel key on redeploy of service
N/A
N/A
> Fix to preserve service specific Sentinel key on redeployment

- templates/powershell/build/ImportAppConfig.ps1
Removed AdoVariableNames debug log from Import app config.
[AB#380527](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/380527)
> 380527:AdoVariableNames debug log

- templates/powershell/build/GetVariablesFromAdo.ps1
Variables defined with explicit types .
[AB#380527](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/380527)
> 380527:Variables defined with explicit types

- templates/powershell/build/PreImportAppConfigCheck.ps1
Throw exception only if has errors
[AB#380527](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/380527)
> 380527:Throw exception only if has errors

- templates/pipelines/common-app-ci.yaml
- templates/powershell/modules/resource-provision/resource-provision.psm1
- templates/powershell/test/Delete-Resources.ps1
- templates/powershell/test/Provision-Resources.ps1
- templates/steps/pre-deployment-tests.yaml
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
> Test resource name

- templates/steps/sonar-analysis-prepare.yaml
- templates/steps/sonar-analysis.yaml
Update sonar task to latest version
Relates to ADO Work Item [AB#395808](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/395808)
N/A
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=582879&view=results
> 395808: Update sonar task to latest version

- templates/pipelines/common-app-ci.yaml
- templates/powershell/build/BuildAndDeployBackstageApp.ps1
- templates/powershell/build/BuildAndPushDockerImage.ps1
- templates/steps/common-app-cd.yaml
Changed 'Docker Build Image' task to AzureCLI to  use base images from ADP shared ACR.
Added WorkingDirectory and  BaseImagesAcrName parameters 
[AB#400560](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/400560)
> 400560: Docker Build Image

- docs/AppBuildAndDeploy.md
- docs/PortalAppBuildAndDeploy.md
- docs/TechDocsPublish.md
- tests/devops/pipelines/pipeline.common.integrationtest.yaml
*Link to the relevant work items: *
[AB#407772](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/407772)
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
> 407772: Renamed service connection to DEFRA-ADP

- tests/devops/pipelines/pipeline.common.integrationtest.yaml
*Link to the relevant work items: *
[AB#410790](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/410790)
Included paths for trigger
> 410790: trigger only for specific file changes 

- templates/pipelines/common-app-ci.yaml
*Link to the relevant work items:*
[AB#411857](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/411857)
> 411857: support multiple post deployment env
